import 'dotenv/config';
import { mkdirSync, writeFileSync } from 'fs';
import { connect } from './supabaseImportUtils';
import { canonicalize, fieldReport, hash, loadSource, parseOptions } from './catalogMigrationCore';
import { catalogAudit, loadCatalogRows } from './catalogIdentity';
import { assertCatalogSchema } from './catalogSchemaPreflight';

const comparableScalar=['legacy_mongo_id','slug','name','description','language','country','image_url','thumbnail_url','thumbnail_alt_text','video_url','cuisine','type','effort','calories_level','popular','dish_register','visibility','spice_level','source','season','diet','mood','prep_time_minutes','cook_time_minutes','total_time_minutes','total_time_tier','num_servings','yields','nutrition','nutrition_visibility','user_ratings','price','status','approved_at','quality_score','owner_id','is_custom','created_at','updated_at'];
const normalized=(v:any):any=>v instanceof Date?v.toISOString():Array.isArray(v)?v.map(normalized):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,normalized(v[k])])):v==null?null:v;
export const normalizeScalar=(field:string,v:any):any=>{
  if(v==null)return null;if(['quality_score','prep_time_minutes','cook_time_minutes','total_time_minutes','num_servings'].includes(field)&&v!=='')return Number(v);
  if(['created_at','updated_at','approved_at'].includes(field)){const date=new Date(v);return Number.isNaN(date.valueOf())?String(v):date.toISOString();}
  return normalized(v);
};
export function scalarDiffs(expected:Record<string,any>,actual:Record<string,any>){return Object.keys(expected).flatMap(field=>{const source=expected[field],postgres=actual[field],normalizedSource=normalizeScalar(field,source),normalizedPostgres=normalizeScalar(field,postgres),equal=JSON.stringify(normalizedSource)===JSON.stringify(normalizedPostgres);return JSON.stringify(normalized(source))===JSON.stringify(normalized(postgres))&&equal?[]:[{field,source,postgres,normalizedSource,normalizedPostgres,status:equal?'equal_after_normalization':'mismatch'}];});}
async function main(){
  const started=Date.now(),options=parseOptions(),raw=await loadSource(options),source=raw.map(canonicalize),db=await connect(),mismatches:any[]=[];
  try{await assertCatalogSchema(db);const catalogRows=await loadCatalogRows(db),audit=catalogAudit(source,catalogRows);for(const {dish,resolution} of audit.resolved){if(resolution.action==='unresolved_duplicate'){mismatches.push({id:dish.legacyId,slug:dish.scalar.slug,areas:['identity'],duplicateCandidates:resolution.matches});continue;}const targetId=resolution.targetId!;const scalarFields=comparableScalar.filter(x=>!['created_at','updated_at'].includes(x)||dish.scalar[x]!=null);const main=await db.query(`select ${scalarFields.map(x=>x==='quality_score'?'quality_score::text quality_score':x).join(',')} from dishes where id=$1`,[targetId]);if(!main.rowCount){mismatches.push({id:dish.legacyId,slug:dish.scalar.slug,areas:['missing dish']});continue;}
    const expectedScalar=Object.fromEntries(scalarFields.map(k=>[k,k==='legacy_mongo_id'?dish.legacyId:dish.scalar[k]??null]));
    const diffs=scalarDiffs(expectedScalar,main.rows[0]),trueScalarDiffs=diffs.filter(diff=>diff.status==='mismatch');
    const tags=(await db.query('select position,name,display_name,type,value from dish_tags where dish_id=$1 order by position',[targetId])).rows;
    const sections=(await db.query(`select s.position,s.name,s.type,json_agg(json_build_object('position',c.position,'ingredient_name',c.ingredient_name,'normalized_name',i.normalized_name,'raw_text',c.raw_text,'original_text',c.original_text,'extra_comment',c.extra_comment,'display_singular',c.display_singular,'display_plural',c.display_plural,'measurements',(select coalesce(json_agg(json_build_object('position',m.position,'quantity',m.quantity::float8,'quantity_text',m.quantity_text,'unit',m.unit,'system',m.system,'text',m.display_text) order by m.position),'[]') from dish_component_measurements m where m.component_id=c.id)) order by c.position) components from dish_sections s left join dish_components c on c.section_id=s.id left join ingredients i on i.id=c.ingredient_id where s.dish_id=$1 group by s.id order by s.position`,[targetId])).rows.map((s:any)=>({...s,components:s.components[0]?.position==null?[]:s.components}));
    const instructions=(await db.query('select position,display_text,start_time,end_time from dish_instructions where dish_id=$1 order by position',[targetId])).rows;
    const areas:string[]=[];if(trueScalarDiffs.length)areas.push('scalars');for(const [area,a,b] of [['tags',dish.tags,tags],['sections/components/measurements',dish.sections,sections],['instructions',dish.instructions,instructions]] as [string,any,any][])if(hash(normalized(a))!==hash(normalized(b)))areas.push(area);if(areas.length)mismatches.push({id:dish.legacyId,slug:dish.scalar.slug,areas,scalarDiffs:diffs,hashes:{source:hash({expectedScalar,tags:dish.tags,sections:dish.sections,instructions:dish.instructions}),postgres:hash({scalar:main.rows[0],tags,sections,instructions})}});
  }
  const ids=audit.resolved.map(x=>x.resolution.targetId).filter((id):id is string=>Boolean(id)),counts:any={MongoDB:{dishes:source.length,tags:0,sections:0,components:0,measurements:0,instructions:0,ingredientsUsed:0},Supabase:{}};const ingredientNames=new Set<string>();for(const d of source){counts.MongoDB.tags+=d.tags.length;counts.MongoDB.sections+=d.sections.length;counts.MongoDB.instructions+=d.instructions.length;for(const s of d.sections)for(const c of s.components){counts.MongoDB.components++;counts.MongoDB.measurements+=c.measurements.length;ingredientNames.add(c.normalized_name);}}counts.MongoDB.ingredientsUsed=ingredientNames.size;
  if(ids.length){const q=await db.query(`select (select count(*) from dishes where id=any($1)) dishes,(select count(*) from dish_tags where dish_id=any($1)) tags,(select count(*) from dish_sections where dish_id=any($1)) sections,(select count(*) from dish_components where dish_id=any($1)) components,(select count(*) from dish_component_measurements m join dish_components c on c.id=m.component_id where c.dish_id=any($1)) measurements,(select count(*) from dish_instructions where dish_id=any($1)) instructions,(select count(distinct ingredient_id) from dish_components where dish_id=any($1)) "ingredientsUsed"`,[ids]);for(const [k,v] of Object.entries(q.rows[0]))counts.Supabase[k]=Number(v);}else counts.Supabase={dishes:0,tags:0,sections:0,components:0,measurements:0,instructions:0,ingredientsUsed:0};
  const staleSupabaseCatalogRows=!options.limit&&!options.dishId&&!options.slug?audit.staleSupabaseCatalogRows:[],spiceLevelWarnings=source.flatMap(dish=>dish.warnings.map(warning=>({dishId:dish.legacyId,slug:dish.scalar.slug??null,name:dish.scalar.name,...warning}))),mapping=fieldReport(raw),countMatch=Object.keys(counts.MongoDB).every(k=>counts.MongoDB[k]===counts.Supabase[k]),passed=mismatches.length===0&&countMatch&&audit.duplicateDishCandidates.length===0&&(!options.failOnStale||staleSupabaseCatalogRows.length===0),report={generatedAt:new Date().toISOString(),durationMs:Date.now()-started,status:passed?'PASS':'FAIL',passed:source.length-mismatches.length,failed:mismatches.length,counts,mismatches,spiceLevelWarnings,staleSupabaseCatalogRows,duplicateDishCandidates:audit.duplicateDishCandidates,unsupportedFields:mapping.filter(x=>x.status==='unsupported_missing_schema'),intentionallyIgnoredFields:mapping.filter(x=>x.status==='intentionally_ignored')};mkdirSync('reports',{recursive:true});writeFileSync('reports/mongo-supabase-catalog-validation.json',JSON.stringify(report,null,2));const table=Object.keys(counts.MongoDB).map(k=>`| ${k} | ${counts.MongoDB[k]} | ${counts.Supabase[k]} |`).join('\n');writeFileSync('reports/mongo-supabase-catalog-validation.md',`# MongoDB → Supabase catalog validation\n\n**${report.status}** — ${report.passed} passed, ${report.failed} failed (${report.durationMs} ms).\n\n| Entity | MongoDB | Supabase |\n|---|---:|---:|\n${table}\n\n## Mismatches\n\n${mismatches.length?'```json\n'+JSON.stringify(mismatches,null,2)+'\n```':'None.'}\n\n## Spice-level warnings\n\n${spiceLevelWarnings.length?'```json\n'+JSON.stringify(spiceLevelWarnings,null,2)+'\n```':'None.'}\n\n## Stale Supabase catalog rows\n\n${staleSupabaseCatalogRows.length?'```json\n'+JSON.stringify(staleSupabaseCatalogRows,null,2)+'\n```':'None.'}\n\n## Unsupported fields\n\n${report.unsupportedFields.map(x=>`- \`${x.mongoField}\``).join('\n')||'None.'}\n`);console.log(JSON.stringify(report,null,2));if(!passed)process.exitCode=1;
  }finally{await db.end();}
}
if(require.main===module)main().catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1;});
