import { createClient } from '@supabase/supabase-js';import { env } from '../../../config/env';import { supabaseConfig } from '../../../config/supabase';import { AppError } from '../../../core/errors/AppError';import { AuthRequest } from '../../../core/middleware/authMiddleware';import { getSupabaseAdminClient } from '../../../shared/db/supabaseAdminClient';import { MeasurementPreference,supabaseProfileService } from './supabaseProfileService';
export class AuthService{
 async supabaseMe(req:AuthRequest){if(!req.authUser||!req.profile)throw new AppError('Unauthorized',401);return{user:supabaseProfileService.toUserDto(req.profile,req.authUser),requireEmailVerification:env.REQUIRE_EMAIL_VERIFICATION&&!req.authUser.email_confirmed_at};}
 async updateSupabasePreferences(req:AuthRequest,p:MeasurementPreference){if(!req.authUser)throw new AppError('Unauthorized',401);const profile=await supabaseProfileService.updatePreference(req.authUser,p);return{user:supabaseProfileService.toUserDto(profile,req.authUser)};}
 async register(email:string,password:string,displayName:string,..._rest:any[]){const {data,error}=await getSupabaseAdminClient().auth.admin.createUser({email:email.trim().toLowerCase(),password,user_metadata:{display_name:displayName},email_confirm:true});if(error||!data.user)throw new AppError(error?.message==='A user with this email address has already been registered'?'Email already in use':'Registration failed',error?.status??400);await supabaseProfileService.ensureProfile(data.user);return this.login(email,password);}
 async login(email:string,password:string,..._rest:any[]){if(!supabaseConfig.anonKey)throw new AppError('Authentication service is not ready',503);const client=createClient(supabaseConfig.url,supabaseConfig.anonKey,{auth:{persistSession:false}});const {data,error}=await client.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error||!data.session||!data.user)throw new AppError('Invalid credentials',401);const profile=await supabaseProfileService.ensureProfile(data.user);return{token:data.session.access_token,accessToken:data.session.access_token,refreshToken:data.session.refresh_token,user:supabaseProfileService.toUserDto(profile,data.user),requireEmailVerification:env.REQUIRE_EMAIL_VERIFICATION&&!data.user.email_confirmed_at};}
 async refresh(refreshToken:string,..._rest:any[]){if(!refreshToken||!supabaseConfig.anonKey)throw new AppError('Refresh token is required',400);const client=createClient(supabaseConfig.url,supabaseConfig.anonKey,{auth:{persistSession:false}});const {data,error}=await client.auth.refreshSession({refresh_token:refreshToken});if(error||!data.session||!data.user)throw new AppError('Invalid refresh token',401);const profile=await supabaseProfileService.ensureProfile(data.user);return{token:data.session.access_token,accessToken:data.session.access_token,refreshToken:data.session.refresh_token,user:supabaseProfileService.toUserDto(profile,data.user)};}
 async logout(..._rest:any[]){return{success:true};}async logoutAll(userId:string){await getSupabaseAdminClient().auth.admin.signOut(userId,'global');return{success:true};}
 async resendVerification(..._rest:any[]){return{success:true};}async verifyEmail(..._rest:any[]){return{success:true};}
}
