import { AppError } from '../../../core/errors/AppError';
import { domainRepositories } from '../../../infrastructure/repositories/domainRepositories';
import { loadMongoDishesInPostgresOrder, mongoDishId, postgresDishId } from '../../../shared/db/dishIdMapping';
import { CatalogDish as DishDocument, postgresDishes } from '../../../infrastructure/postgres/repositories/PostgresCatalogRepositories';
import { DISH_DTO_SELECT, toDishDto, toPublicDishId } from '../../dishes/dto/dishDto';
import { LastFilterPresetService, normalizeFilterList } from '../../filters/services/lastFilterPresetService';
import { buildRecommendedDeck, DeckRecommendationHistoryEntry, RecommendedDeckMeta } from '../../recommendations/deckRecommendationService';
import { logRecommendationMeta } from '../../recommendations/recommendationTypes';
import { dishMatchesExclusions } from '../../../shared/ingredients/exclusionMatcher';
const MAX_DECK_SIZE=30;
type SoloFilterInput={dishRegisters?:string[];includeCustomDishesFirst?:boolean;cuisines?:string[];moods?:string[];diet?:string[];exclusions?:string[]};
type NormalizedSoloFilter={dishRegisters:string[];includeCustomDishesFirst:boolean;cuisines:string[];moods:string[];diet:string[];exclusions:string[]};
type DeckBuildResult={dishes:DishDocument[];meta:RecommendedDeckMeta};
export class SoloSwipeService {
 async getActive(userId:string){const s=await domainRepositories.soloSessions.findActive(userId);if(s)await domainRepositories.soloSessions.update(s.id,userId,{});return s?this.toDeck(s):null;}
 async getResumable(userId:string){const s=await domainRepositories.soloSessions.findResumable(userId);return s?this.toDeck(s):null;}
 async createSession(userId:string,filter:SoloFilterInput){await this.assertNoActiveSession(userId);const normalized=this.normalizeFilter(filter),result=await this.buildDeck(userId,normalized);logRecommendationMeta(result.meta);const ids=await Promise.all(result.dishes.map(postgresDishId));const s=await domainRepositories.soloSessions.create({userId,deckDishIds:ids,filters:normalized,algorithm:result.meta.algorithm,meta:result.meta as unknown as Record<string,unknown>});return this.toDeck(s,result.dishes,result.meta);}
 async getDeck(userId:string,id:string){const s=await this.requireSession(userId,id);return this.toDeck(s);}
 async updateActiveFilter(userId:string,filter:SoloFilterInput){const s=await domainRepositories.soloSessions.findActive(userId);if(!s)throw new AppError('No active solo session',404,'NO_ACTIVE_SESSION');const normalized=this.normalizeFilter(filter),swipes=await domainRepositories.swipes.listForUserSession(userId,s.id,'solo');const oldMongo=await Promise.all(s.deckDishIds.map(mongoDishId));const excluded=new Set((await Promise.all(swipes.map(x=>mongoDishId(x.dishId)))).filter((x):x is string=>!!x));const result=await this.buildDeck(userId,normalized,excluded,new Set(oldMongo.filter((x):x is string=>!!x))),ids=await Promise.all(result.dishes.map(postgresDishId));const updated=await domainRepositories.soloSessions.update(s.id,userId,{filters:normalized,deckDishIds:ids,currentIndex:0,meta:result.meta as unknown as Record<string,unknown>,algorithm:result.meta.algorithm});return this.toDeck(updated!,result.dishes,result.meta);}
 async abandonActive(userId:string){const s=await domainRepositories.soloSessions.setStatusForActive(userId,'abandoned');return{ok:true,abandoned:Boolean(s),sessionId:s?.id??null};}
 async swipe(userId:string,id:string,dishId:string,direction:'like'|'dislike'){const s=await this.requireSession(userId,id),dish=await postgresDishes.getByPublicId(dishId);if(!dish)throw new AppError('This dish is not available.',404);const pg=await postgresDishId(dish);if(s.deckDishIds[s.currentIndex]!==pg)throw new AppError('Dish is not current in this solo session.',409,'DISH_NOT_CURRENT');if(!this.isSoloVisibleDish(dish,userId))throw new AppError('This dish is not available.',404);const swipe=await domainRepositories.swipes.createOnce({userId,dishId:pg,mode:'solo',direction,soloSessionId:id});let matchCreated=false;if(swipe.swipe.direction==='like'){const m=await domainRepositories.matches.createOnce({dishId:pg,mode:'solo',userId});matchCreated=m.created;}const next=Math.min(s.currentIndex+1,s.deckDishIds.length),completed=next>=s.deckDishIds.length;await domainRepositories.soloSessions.update(id,userId,{currentIndex:next,status:completed?'completed':'active',completedAt:completed?new Date():null});if(completed)await new LastFilterPresetService().saveLast(userId,{mode:'solo',...(s.filters as NormalizedSoloFilter),matchedLastTime:(await domainRepositories.matches.listForUser(userId,'solo')).length});return{id:swipe.swipe.id,dishId:toPublicDishId(dish),direction:swipe.swipe.direction,matchCreated,alreadySwiped:!swipe.created,completed,mode:'solo'};}
 async undo(userId:string,id:string){const s=await domainRepositories.soloSessions.findByIdForUser(id,userId);if(!s||!['active','completed'].includes(s.status))throw new AppError('No solo session found',404,'NO_ACTIVE_SESSION');const swipe=await domainRepositories.swipes.deleteLatest(userId,id,'solo'),expected=s.deckDishIds[s.currentIndex-1];if(!swipe||swipe.dishId!==expected)return{undone:false,lastUndoneDishId:null,session:await this.toDeck(s)};if(swipe.direction==='like')await domainRepositories.matches.deleteSolo(userId,swipe.dishId);const updated=await domainRepositories.soloSessions.update(id,userId,{currentIndex:Math.max(0,s.currentIndex-1),status:'active',completedAt:null});return{undone:true,lastUndoneDishId:await mongoDishId(swipe.dishId),session:await this.toDeck(updated!)};}
 async assertNoActiveSession(userId:string){const [solo,pair]=await Promise.all([domainRepositories.soloSessions.findActive(userId),domainRepositories.coupleSessions.findActiveForUser(userId)]);if(solo||pair)throw new AppError('You already have an active swipe session.',409,'ACTIVE_SESSION_EXISTS');}
 private normalizeFilter(f:SoloFilterInput):NormalizedSoloFilter{return{dishRegisters:normalizeFilterList(f.dishRegisters),includeCustomDishesFirst:f.includeCustomDishesFirst===true,cuisines:normalizeFilterList(f.cuisines),moods:normalizeFilterList(f.moods),diet:normalizeFilterList(f.diet),exclusions:normalizeFilterList(f.exclusions)}}
 private async requireSession(u:string,id:string){const s=await domainRepositories.soloSessions.findByIdForUser(id,u);if(!s||s.status!=='active')throw new AppError('No active solo session',404,'NO_ACTIVE_SESSION');return s;}
 private async toDeck(s:any,loaded?:DishDocument[],meta?:RecommendedDeckMeta){const ids=s.deckDishIds.slice(s.currentIndex),dishes=loaded??await loadMongoDishesInPostgresOrder(ids);return{sessionId:s.id,mode:'solo',status:s.status,deckIndex:s.currentIndex,matchedCount:(await domainRepositories.matches.listForUser(s.userId,'solo')).length,filter:s.filters,dishes:dishes.map(toDishDto).filter(Boolean),meta:{totalCatalogCount:(meta??s.meta)?.totalCatalogCount??s.deckDishIds.length,candidateCount:(meta??s.meta)?.candidateCount??s.deckDishIds.length,finalCount:ids.length,usedPartnerChoices:false,bothConfirmed:false,recommendationMeta:meta??s.meta,algorithm:(meta??s.meta)?.algorithm}};}
 private async buildDeck(userId:string,filter:NormalizedSoloFilter,excludeDishIds=new Set<string>(),recentlySeenDishIds=new Set<string>()):Promise<DeckBuildResult>{const runtime=userId;const all=await postgresDishes.list(userId),history=await this.loadUserHistory(userId);const result=buildRecommendedDeck({userId,dishes:all,filters:filter,userHistory:history,recentlySeenDishIds,excludedDishIds:excludeDishIds,deckSize:MAX_DECK_SIZE,mode:'solo'});if(!filter.includeCustomDishesFirst){logDeckOrder('solo',false,[],result.dishes);return result;}const custom=all.filter(d=>isUsableOwnedCustomDish(d,runtime)&&!excludeDishIds.has(d._id.toString())&&!dishMatchesExclusions(d,filter.exclusions)&&matchesCustomDiet(d,filter.diet)).sort((a,b)=>compareCustomByPreferences(a,b,filter));const customIds=new Set(custom.map(d=>d._id.toString())),prefix=custom.slice(0,MAX_DECK_SIZE),tail=result.dishes.filter(d=>!customIds.has(d._id.toString())).slice(0,MAX_DECK_SIZE-prefix.length);logDeckOrder('solo',true,prefix,tail);return{...result,dishes:[...prefix,...tail],meta:{...result.meta,finalCount:prefix.length+tail.length,customIncludedCount:prefix.length}};}
 private async loadUserHistory(userId:string):Promise<DeckRecommendationHistoryEntry[]>{const [solo,pair]=await Promise.all([domainRepositories.soloSessions.findResumable(userId),domainRepositories.coupleSessions.findActiveForUser(userId)]),rows=[] as any[];if(solo)rows.push(...await domainRepositories.swipes.listForUserSession(userId,solo.id,'solo'));if(pair)rows.push(...await domainRepositories.swipes.listForUserSession(userId,pair.id,'paired'));const dishes=await loadMongoDishesInPostgresOrder(rows.map(r=>r.dishId));return rows.map((r,i)=>dishes[i]?{dish:dishes[i],direction:r.direction}:null).filter((x):x is DeckRecommendationHistoryEntry=>!!x);}
 private isSoloVisibleDish(d:DishDocument,u:string){return(d.visibility==='public'&&d.status==='approved')||isUsableOwnedCustomDish(d,u);}
}

function isUsableOwnedCustomDish(dish: DishDocument, userId: string) {
 return (dish.isCustom === true || dish.sourceType === 'custom') && dish.status === 'approved' && dish.createdBy?.toString() === userId;
}

function matchesCustomDiet(dish: DishDocument, diet: string[]) { const values = new Set((dish.diet ?? []).map((value:string) => value.trim().toLowerCase())); if (diet.includes('vegan')) return values.has('vegan'); if (diet.includes('vegetarian')) return values.has('vegetarian') || values.has('vegan'); return true; }

function compareCustomByPreferences(a: DishDocument, b: DishDocument, filters: NormalizedSoloFilter) {
 const registerDelta = preferenceMatch(b.dishRegister ?? (b as any).dish_register, filters.dishRegisters) - preferenceMatch(a.dishRegister ?? (a as any).dish_register, filters.dishRegisters);
 if (registerDelta !== 0) return registerDelta;
 const cuisineDelta = preferenceMatch(b.cuisine, filters.cuisines) - preferenceMatch(a.cuisine, filters.cuisines);
 if (cuisineDelta !== 0) return cuisineDelta;
 const dateDelta = customTimestamp(b) - customTimestamp(a);
 return dateDelta || a._id.toString().localeCompare(b._id.toString());
}

function preferenceMatch(value: string | undefined, selected: string[]) { return selected.includes((value ?? '').trim().toLowerCase().replace(/_/g, ' ')) ? 1 : 0; }
function customTimestamp(dish: DishDocument) { return ((dish as any).updatedAt ?? dish.createdAt)?.getTime?.() ?? 0; }
function logDeckOrder(mode: 'solo', customFirst: boolean, prefix: DishDocument[], tail: DishDocument[]) {
 const final = [...prefix, ...tail];
 console.log(`[DeckOrder] mode=${mode} customFirst=${customFirst} customPrefixCount=${prefix.length} tailCount=${tail.length} finalCount=${final.length}`);
 console.log(`[DeckOrder] firstIds=${final.slice(0, 8).map((dish) => dish._id.toString()).join(',')}`);
 console.log('[DeckOrder] noRandomShuffle=true');
}
