import { AppError } from '../../../core/errors/AppError';
import { domainRepositories } from '../../../infrastructure/repositories/domainRepositories';
import { queryPostgres } from '../../../shared/db/postgresClient';
import { entitlementService } from '../../entitlements/services/entitlementService';

export class SharedShoppingListService {
  async list(userId:string){const session=await this.session(userId);const rows=await queryPostgres('select id,name,normalized_name,quantity,measure,checked,sort_order,created_at,updated_at from shared_shopping_list_items where couple_session_id=$1 order by sort_order,created_at',[session.id]);return{sessionId:session.id,items:rows.rows};}
  async add(userId:string,input:{name?:unknown;quantity?:unknown;measure?:unknown}){const session=await this.session(userId),name=String(input.name??'').trim();if(!name)throw new AppError('Item name is required.',400,'SHOPPING_LIST_ITEM_NAME_REQUIRED');const normalized=name.toLowerCase();await queryPostgres(`insert into shared_shopping_list_items(couple_session_id,created_by,name,normalized_name,quantity,measure,sort_order) values($1,$2,$3,$4,$5,$6,(select count(*) from shared_shopping_list_items where couple_session_id=$1)) on conflict(couple_session_id,normalized_name) do update set quantity=coalesce(shared_shopping_list_items.quantity,excluded.quantity),measure=coalesce(shared_shopping_list_items.measure,excluded.measure),updated_at=now()`,[session.id,userId,name,normalized,clean(input.quantity),clean(input.measure)]);return this.list(userId);}
  async update(userId:string,id:string,input:{checked?:unknown}){const session=await this.session(userId);const result=await queryPostgres('update shared_shopping_list_items set checked=coalesce($3,checked),updated_at=now() where id=$1 and couple_session_id=$2 returning id',[id,session.id,typeof input.checked==='boolean'?input.checked:null]);if(!result.rowCount)throw new AppError('Shopping-list item not found.',404,'SHOPPING_LIST_ITEM_NOT_FOUND');return this.list(userId);}
  async remove(userId:string,id:string){const session=await this.session(userId);const result=await queryPostgres('delete from shared_shopping_list_items where id=$1 and couple_session_id=$2',[id,session.id]);if(!result.rowCount)throw new AppError('Shopping-list item not found.',404,'SHOPPING_LIST_ITEM_NOT_FOUND');return this.list(userId);}
  private async session(userId:string){const session=await domainRepositories.coupleSessions.findActiveForUser(userId);if(!session||!session.memberIds.includes(userId))throw new AppError('An active pair is required.',404,'PAIR_SESSION_INACTIVE');if(!await entitlementService.canPairUseFeature(session,'shared_shopping_list'))throw new AppError('FoodMatch Premium is required for shopping lists.',403,'PREMIUM_SHOPPING_LIST_REQUIRED',{feature:'shopping_list'});return session;}
}
function clean(value:unknown){const result=String(value??'').trim();return result||null;}
