import { AppError } from '../../../core/errors/AppError';
import { postgresDishes } from '../../../infrastructure/postgres/repositories/PostgresCatalogRepositories';
import { toDishDto } from '../dto/dishDto';

export interface DishListFilters { search?:string;cuisine?:string[];type?:string[];mood?:string[];diet?:string[];effort?:string;popular?:boolean;source?:string;season?:string[];mealType?:string[];maxCookTime?:number;maxTotalTime?:number;timeTier?:string[];maxIngredients?:number;minCalories?:number;maxCalories?:number }
export interface DishListOptions extends DishListFilters { limit:number;offset:number;sort?:string }
export interface PaginatedDishResult {items:any[];total:number;limit:number;offset:number;hasMore:boolean}
interface CreateCustomDishInput {name:string;cuisine:string;mood:string|string[];dishRegister:string;type?:string;description?:string;diet?:string[];source?:string[];season?:string[];ingredients:Array<{name:string;quantity?:string;unit?:string}>;cookTime:number;servings:string;steps:Array<{step:number;text:string}>;imageUrl?:string;imagePublicId?:string}
export class DishService {
 async listDishes(userId:string,query?:string,returnAll=false){let rows=await postgresDishes.listLightweight(userId);if(query)rows=this.filter(rows,{search:query});return rows.slice(0,returnAll?undefined:50).map(toDishDto).filter(Boolean);}
 async listDishesPage(userId:string,o:DishListOptions):Promise<PaginatedDishResult>{let rows=this.filter(await postgresDishes.listLightweight(userId),o);if(o.sort==='cookTime')rows.sort((a,b)=>(a.cookTime??0)-(b.cookTime??0)||a.name.localeCompare(b.name));const total=rows.length,items=rows.slice(o.offset,o.offset+o.limit).map(toDishDto).filter(Boolean);return{items,total,limit:o.limit,offset:o.offset,hasMore:o.offset+items.length<total};}
 async searchDishes(userId:string,q:string){return this.listDishes(userId,q);}
 async getDishById(userId:string,id:string){const d=await postgresDishes.getByPublicId(id.trim());if(!d||!this.visible(d,userId))throw new AppError('Dish not found',404,'DISH_NOT_FOUND');return toDishDto(d);}
 async getRandomDish(userId:string){const all=await postgresDishes.list(userId);if(!all.length)throw new AppError('Dish not found',404,'DISH_NOT_FOUND');return toDishDto(all[Math.floor(Math.random()*all.length)]);}
 async createCustomDish(userId:string,input:CreateCustomDishInput){return toDishDto(await postgresDishes.createCustomDish(userId,this.clean(input)));}
 async updateMyCustomDish(userId:string,id:string,input:CreateCustomDishInput){const result=await postgresDishes.updateCustomDish(userId,id,this.clean(input));if(result==='forbidden')throw new AppError('You can only edit your own dishes.',403,'CUSTOM_DISH_FORBIDDEN');if(!result)throw new AppError('Custom dish not found',404,'CUSTOM_DISH_NOT_FOUND');return toDishDto(result);}
 async listMyCustomDishes(userId:string){return (await postgresDishes.listMyCustomDishes(userId)).map(toDishDto).filter(Boolean);}
 async deleteMyCustomDish(userId:string,id:string){const result=await postgresDishes.deleteCustomDish(userId,id);if(result==='forbidden')throw new AppError('You can only delete your own dishes.',403,'CUSTOM_DISH_FORBIDDEN');if(result==='missing')throw new AppError('Custom dish not found',404,'CUSTOM_DISH_NOT_FOUND');return{deleted:true};}
 private clean(i:CreateCustomDishInput){return{...i,name:i.name.trim(),cuisine:i.cuisine.trim(),mood:(Array.isArray(i.mood)?i.mood:[i.mood]).map(x=>x.trim()).filter(Boolean),dishRegister:i.dishRegister.trim().toLowerCase(),ingredients:i.ingredients.map(x=>({...x,name:x.name.trim()})).filter(x=>x.name),steps:i.steps.map((x,n)=>({step:x.step??n+1,text:x.text.trim()})).filter(x=>x.text),cookTime:Math.max(0,Math.trunc(i.cookTime||0)),servings:i.servings.trim()};}
 private visible(d:any,u:string){return d.status==='approved'&&(d.visibility==='public'||d.ownerId===u);}
 private filter(rows:any[],f:DishListFilters){const includes=(v:any,x?:string[])=>!x?.length||x.map(y=>y.toLowerCase()).includes(String(v??'').toLowerCase());return rows.filter(d=>(!f.search||`${d.name} ${d.description??''} ${(d.ingredients??[]).join(' ')}`.toLowerCase().includes(f.search.toLowerCase()))&&includes(d.cuisine,f.cuisine)&&includes(d.type,f.type)&&(!f.diet?.length||f.diet.every(x=>(d.diet??[]).map((y:string)=>y.toLowerCase()).includes(x.toLowerCase())))&&(f.popular===undefined||d.popular===f.popular)&&(!f.maxCookTime||(d.cookTime??0)<=f.maxCookTime));}
}
