import { AppError } from '../../../core/errors/AppError';
import { domainRepositories } from '../../../infrastructure/repositories/domainRepositories';
export interface LastFilterPayload { mode:'solo'|'paired'; selectedCategories?:string[]; dishRegisters?:string[]; includeCustomDishesFirst?:boolean; cuisines?:string[]; moods?:string[]; diet?:string[]; exclusions?:string[]; matchedLastTime?:number; }
export function normalizeFilterList(values?:string[]){if(!Array.isArray(values))return[];return[...new Set(values.map(v=>(v??'').trim().toLowerCase()).filter(Boolean))].slice(0,50);}
export function buildPairKey(ids:string[]){return ids.slice().sort().join('_');}
function dto(row:any){if(!row)return null;const f=row.filters??{},categories=f.selectedCategories??f.dishRegisters??(f.category?[f.category]:[]);return{id:row.id,mode:row.mode,userId:row.userId,pairKey:row.pairKey,selectedCategories:categories,dishRegisters:categories,includeCustomDishesFirst:f.includeCustomDishesFirst===true,cuisines:f.cuisines??[],moods:f.moods??[],diet:f.diet??[],exclusions:f.exclusions??[],matchedLastTime:f.matchedLastTime??0,usedAt:row.usedAt,createdAt:row.createdAt,updatedAt:row.updatedAt};}
export class LastFilterPresetService {
 async getLast(userId:string,mode:'solo'|'paired'){const pairKey=mode==='paired'?await this.pairKey(userId):null;return dto(await domainRepositories.filterPresets.findLast(userId,mode,pairKey));}
 async hasLegacyPairedPreset(_userId?:string){return false;}
 async saveLast(userId:string,p:LastFilterPayload){const pairKey=p.mode==='paired'?await this.pairKey(userId):null;const categories=normalizeFilterList(p.selectedCategories??p.dishRegisters);const filters={selectedCategories:categories,dishRegisters:categories,includeCustomDishesFirst:p.includeCustomDishesFirst===true,cuisines:normalizeFilterList(p.cuisines),moods:normalizeFilterList(p.moods),diet:normalizeFilterList(p.diet),exclusions:normalizeFilterList(p.exclusions),matchedLastTime:Math.max(0,Math.min(10000,Number(p.matchedLastTime??0)||0))};return dto(await domainRepositories.filterPresets.upsert({userId,mode:p.mode,pairKey,filters,isMeaningful:Object.entries(filters).some(([k,v])=>k==='includeCustomDishesFirst'?v===true:k==='matchedLastTime'?false:Array.isArray(v)&&v.length>0)}));}
 private async pairKey(userId:string){const s=await domainRepositories.coupleSessions.findActiveForUser(userId);if(!s||s.memberIds.length<2)throw new AppError('No active paired session',404,'NO_ACTIVE_SESSION');return s.pairKey??buildPairKey(s.memberIds);}
}
